apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-file
          emptyDir: {}
      containers:
        - name: log-output-generator
          image: eokarnas/dwk-log-output-generator:1.10
          volumeMounts:
            - name: shared-file
              mountPath: /app/files
        - name: log-output-reader
          image: eokarnas/dwk-log-output-reader:1.10
          volumeMounts:
            - name: shared-file
              mountPath: /app/files
